// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewOrderInput struct {
	ProjectName string  `json:"project_name"`
	ExpiredAt   *string `json:"expired_at"`
	CustomerIid string  `json:"customer_iid"`
}

type NewTodoInput struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Order struct {
	ID                    string           `json:"id"`
	InternalID            string           `json:"internal_id"`
	ProjectName           string           `json:"project_name"`
	AgreementID           int              `json:"agreement_id"`
	BargeID               int              `json:"barge_id"`
	AcceptedOfferID       int              `json:"accepted_offer_id"`
	ExpiredAt             string           `json:"expired_at"`
	CustomerIid           string           `json:"customer_iid"`
	CustomerName          string           `json:"customer_name"`
	CustomerImageURL      string           `json:"customer_image_url"`
	CustomerPicName       string           `json:"customer_pic_name"`
	CustomerPicPhone      string           `json:"customer_pic_phone"`
	CustomerRequestNumber string           `json:"customer_request_number"`
	CustomerOrderNumber   string           `json:"customer_order_number"`
	AcceptedOrderVendorID string           `json:"accepted_order_vendor_id"`
	VendorOrderNumber     string           `json:"vendor_order_number"`
	Route                 string           `json:"route"`
	TotalLoadingRate      float64          `json:"total_loading_rate"`
	TotalWeightTon        float64          `json:"total_weight_ton"`
	TotalVolumeCbm        float64          `json:"total_volume_cbm"`
	Status                int              `json:"status"`
	Notes                 string           `json:"notes"`
	CancelReason          string           `json:"cancel_reason"`
	CancelledAt           *string          `json:"cancelled_at"`
	CancelledBy           string           `json:"cancelled_by"`
	AcceptedAt            *string          `json:"accepted_at"`
	AcceptedBy            string           `json:"accepted_by"`
	IsDeleted             bool             `json:"is_deleted"`
	CreatedAt             string           `json:"created_at"`
	CreatedBy             string           `json:"created_by"`
	UpdatedAt             string           `json:"updated_at"`
	UpdatedBy             string           `json:"updated_by"`
	DeletedAt             *string          `json:"deleted_at"`
	DeletedBy             string           `json:"deleted_by"`
	OrderLoads            []*OrderLoad     `json:"order_loads"`
	OrderLocations        []*OrderLocation `json:"order_locations"`
}

type OrderLoad struct {
	ID               string  `json:"id"`
	InternalID       string  `json:"internal_id"`
	OrderID          int     `json:"order_id"`
	GoodsType        string  `json:"goods_type"`
	VolumeCbm        float64 `json:"volume_cbm"`
	WeightTon        float64 `json:"weight_ton"`
	LoadingRate      float64 `json:"loading_rate"`
	PickupDatetime   string  `json:"pickup_datetime"`
	DeliveryDatetime string  `json:"delivery_datetime"`
}

type OrderLocation struct {
	ID         string  `json:"id"`
	InternalID string  `json:"internal_id"`
	OrderID    int     `json:"order_id"`
	Sequence   int     `json:"sequence"`
	LocationID int     `json:"location_id"`
	Name       string  `json:"name"`
	Address    string  `json:"address"`
	City       string  `json:"city"`
	District   string  `json:"district"`
	Village    string  `json:"village"`
	Postcode   string  `json:"postcode"`
	PlusCode   string  `json:"plus_code"`
	Latitude   float64 `json:"latitude"`
	Longitude  float64 `json:"longitude"`
	IsLoad     bool    `json:"is_load"`
	IsUnload   bool    `json:"is_unload"`
	CreatedAt  *string `json:"created_at"`
	CreatedBy  string  `json:"created_by"`
	UpdatedAt  *string `json:"updated_at"`
	UpdatedBy  string  `json:"updated_by"`
	DeletedAt  *string `json:"deleted_at"`
	DeletedBy  string  `json:"deleted_by"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
